name: Release
on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    branches: [main, beta, alpha]
jobs:
  release:
    name: Release
    environment: staging
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run package
        env:
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          BUILD_LANGUAGES: ${{ secrets.BUILD_LANGUAGES }}
          BUILD_CMS: ${{ BUILD_CMS }}
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
